-- Pup Portrait Database Schema
-- Migration: 00001_initial_schema

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- PROFILES TABLE
-- Extends Supabase auth.users with app-specific data
-- ============================================
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  display_name TEXT,
  avatar_url TEXT,
  subscription_tier TEXT DEFAULT 'free' CHECK (subscription_tier IN ('free', 'premium', 'lifetime')),
  subscription_status TEXT CHECK (subscription_status IN ('active', 'canceled', 'expired', 'past_due', NULL)),
  stripe_customer_id TEXT UNIQUE,
  daily_generations_used INTEGER DEFAULT 0,
  daily_reset_at TIMESTAMP WITH TIME ZONE,
  total_generations INTEGER DEFAULT 0,
  lifetime_credits INTEGER DEFAULT 0, -- For lifetime plan users
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- PORTRAITS TABLE
-- Stores generated dog portraits
-- ============================================
CREATE TABLE portraits (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  breed TEXT NOT NULL,
  color TEXT,
  background TEXT,
  style TEXT DEFAULT 'realistic' CHECK (style IN ('realistic', 'cartoon', 'watercolor', 'artistic')),
  name TEXT NOT NULL, -- Generated dog name
  image_url TEXT NOT NULL,
  thumbnail_url TEXT,
  prompt TEXT, -- The prompt sent to Nano Banana
  resolution INTEGER DEFAULT 512,
  is_premium BOOLEAN DEFAULT FALSE,
  is_public BOOLEAN DEFAULT FALSE,
  is_guest BOOLEAN DEFAULT FALSE, -- True if generated by anonymous user
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- SUBSCRIPTIONS TABLE
-- Tracks Stripe subscriptions
-- ============================================
CREATE TABLE subscriptions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  stripe_subscription_id TEXT UNIQUE,
  stripe_price_id TEXT,
  plan_type TEXT NOT NULL CHECK (plan_type IN ('monthly', 'yearly', 'lifetime')),
  amount INTEGER NOT NULL, -- Amount in cents
  status TEXT NOT NULL CHECK (status IN ('active', 'canceled', 'expired', 'past_due', 'incomplete')),
  current_period_start TIMESTAMP WITH TIME ZONE,
  current_period_end TIMESTAMP WITH TIME ZONE,
  cancel_at_period_end BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- EMAIL SIGNUPS TABLE
-- For newsletter subscriptions
-- ============================================
CREATE TABLE email_signups (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email TEXT UNIQUE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  source TEXT DEFAULT 'website', -- Where they signed up from
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- GUEST GENERATIONS TABLE
-- Track anonymous user generations (for rate limiting)
-- ============================================
CREATE TABLE guest_generations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  device_fingerprint TEXT NOT NULL,
  ip_address TEXT,
  portrait_id UUID REFERENCES portraits(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX idx_profiles_stripe_customer ON profiles(stripe_customer_id);
CREATE INDEX idx_profiles_subscription_tier ON profiles(subscription_tier);
CREATE INDEX idx_portraits_user_id ON portraits(user_id);
CREATE INDEX idx_portraits_created_at ON portraits(created_at DESC);
CREATE INDEX idx_portraits_is_public ON portraits(is_public) WHERE is_public = TRUE;
CREATE INDEX idx_subscriptions_user_id ON subscriptions(user_id);
CREATE INDEX idx_subscriptions_status ON subscriptions(status);
CREATE INDEX idx_guest_generations_fingerprint ON guest_generations(device_fingerprint);
CREATE INDEX idx_guest_generations_created ON guest_generations(created_at DESC);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================

-- Enable RLS on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE portraits ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_signups ENABLE ROW LEVEL SECURITY;
ALTER TABLE guest_generations ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "Users can view own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Portraits policies
CREATE POLICY "Users can view own portraits" ON portraits
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can view public portraits" ON portraits
  FOR SELECT USING (is_public = TRUE);

CREATE POLICY "Users can insert own portraits" ON portraits
  FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can update own portraits" ON portraits
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own portraits" ON portraits
  FOR DELETE USING (auth.uid() = user_id);

-- Subscriptions policies
CREATE POLICY "Users can view own subscriptions" ON subscriptions
  FOR SELECT USING (auth.uid() = user_id);

-- Email signups - insert only (no viewing by users)
CREATE POLICY "Anyone can sign up for newsletter" ON email_signups
  FOR INSERT WITH CHECK (TRUE);

-- Guest generations - service role only (handled by edge functions)
-- No user-facing policies needed

-- ============================================
-- FUNCTIONS & TRIGGERS
-- ============================================

-- Function to create profile on user signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, email, display_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name'),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to auto-create profile
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- Function to reset daily generations at midnight
CREATE OR REPLACE FUNCTION reset_daily_generations()
RETURNS void AS $$
BEGIN
  UPDATE profiles
  SET
    daily_generations_used = 0,
    daily_reset_at = NOW()
  WHERE
    daily_reset_at IS NULL
    OR daily_reset_at < CURRENT_DATE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_subscriptions_updated_at
  BEFORE UPDATE ON subscriptions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
